### PR TITLE
Update Material.Icons package reference to v1.1.10

### PR DESCRIPTION
**Pull request by javidsho**

### CODE REVIEW

**Comment by SKProCH** [comment]
Greetings. Why do you need this change?

**Comment by javidsho** [comment]
Hi there
The other package is updated as Material icons change. Why not update this package that depends on the other one?
Since it contains an enum, the new versions are incompatible with this old one.

**Comment by SKProCH** [comment]
What prevents you from updating Material.Icons version explicitly in your csproj?
You can specify any version of Material.Icons above 1.0.2 and it should work

**Comment by SKProCH** [comment]
You can specify any version of Material.Icons above 1.0.2 and it should work

**Comment by javidsho** [comment]
I tried that already and it didnt work. I installed it independently and the project didnt compile.

**Comment by SKProCH** [comment]
I tried this setup now and it works fine:
```
    <PackageReference Include="Material.Icons" Version="1.1.10" />
    <PackageReference Include="Material.Icons.Avalonia" Version="1.0.2" />
```
Please provide your compilation errors.

**Comment by javidsho** [comment]
`error CS0012: The type 'MaterialIconKind' is defined in an assembly that is not referenced. You must add a reference to assembly 'Material.Icons, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null'.`

I have a shared project that's referencing Material.Icons v1.1.10 and an Avalonia-based project that references the shared project, and Material.Icons.Avalonia v1.0.2. Now it gives me the mentioned error. I tried adding a reference to Material.Icons v1.1.10 as well but nothing changes, same error.

**Comment by SKProCH** [comment]
Can you share your project or provide minimal reproducible example? I want to take a look.

**Comment by javidsho** [comment]
Take a look at this: https://github.com/javidsho/Temp

If I don't do this by code, everything works fine. But look at MainWindow.axaml.cs and you'll see the problem.

**Comment by javidsho** [comment]
What's the problem with releasing a new version?? It doesn't break anything.

**Comment by SKProCH** [comment]
Some really weird behavior. Ok, ill merge this, and try to investigate the problem.

**Comment by SKProCH** [comment]
Thanks for contributing

**Comment by javidsho** [comment]
Cool! Thanks

**Comment by javidsho** [comment]
Yeah it's weird AF

**Pull request merged**
